# ワークフローの名前
name: Go CI

# トリガーになる Github イベント
#　今回は、リポジトリへのコミットと PR 作成をトリガーにします
on:
  push:
  pull_request:

# ジョブ定義
jobs:
  # ジョブ名
  unit-test:
    # ジョブの実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v3
      # Go の実行環境の Set up
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      # テストの実行
      - name: Run Test
        run: go test -v ./...
  golangci-lint:
    # push 時のみ動作するようにする
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          go-version: 1.19
          reporter: github-check
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: added