# ワークフローの名前
name: golangci-lint

on:
  pull_request:

# ジョブ定義
jobs:
  # lint
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          go-version: 1.20
          # reviewdog の動作モードの指定
          reporter: github-pr-review
          # 指摘レベルの指定
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
