# ワークフローの名前
name: golangci-lint

on:
  pull_request:

# ジョブ定義
jobs:
  # lint
  golangci-lint:
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go-version: 1.19
          # reviewdog の動作モードの指定
          reporter: github-pr-review
          # 指摘レベルの指定
          level: warning
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: added